-- Bangalir Utsav: Supabase persistence setup
-- Run this entire file once in Supabase Dashboard -> SQL Editor.
-- It uses dedicated table names so it does not conflict with the old
-- site_state/user_locations schemas from earlier versions of the project.

create table if not exists public.puja_state (
    id bigint primary key,
    pushpanjali_count bigint not null default 14290,
    updated_at timestamptz not null default now()
);

insert into public.puja_state (id, pushpanjali_count)
values (1, 14290)
on conflict (id) do nothing;

create table if not exists public.live_locations (
    id bigint generated by default as identity primary key,
    location text not null,
    created_at timestamptz not null default now()
);

create index if not exists live_locations_created_at_idx
on public.live_locations (created_at desc);

-- Public read for the live counter and public location board.
alter table public.puja_state enable row level security;
alter table public.live_locations enable row level security;

drop policy if exists "public can read puja state" on public.puja_state;
create policy "public can read puja state"
on public.puja_state for select to anon, authenticated using (true);

drop policy if exists "public can read live locations" on public.live_locations;
create policy "public can read live locations"
on public.live_locations for select to anon, authenticated using (true);

drop policy if exists "public can insert live locations" on public.live_locations;
create policy "public can insert live locations"
on public.live_locations for insert to anon, authenticated with check (true);

-- Atomic Pushpanjali increment. The browser/app does not need UPDATE permission.
create or replace function public.increment_pushpanjali()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    new_count bigint;
begin
    update public.puja_state
       set pushpanjali_count = pushpanjali_count + 1,
           updated_at = now()
     where id = 1
     returning pushpanjali_count into new_count;

    if new_count is null then
        raise exception 'puja_state row id=1 is missing';
    end if;

    return new_count;
end;
$$;

revoke all on function public.increment_pushpanjali() from public;
grant execute on function public.increment_pushpanjali() to anon, authenticated;

-- Optional one-time migration helpers for the two older schemas.
-- If these old tables exist, copy their data into the new tables.
do $$
begin
    -- Old site_state(id, pushpanjali_count)
    if to_regclass('public.site_state') is not null then
        begin
            execute 'insert into public.puja_state (id, pushpanjali_count) select 1, pushpanjali_count from public.site_state where id = 1 on conflict (id) do update set pushpanjali_count = excluded.pushpanjali_count';
        exception when undefined_column then null; end;
    end if;

    -- Old site_state(key, value)
    if to_regclass('public.site_state') is not null then
        begin
            execute 'insert into public.puja_state (id, pushpanjali_count) select 1, value::bigint from public.site_state where key = ''pushpanjali_count'' on conflict (id) do update set pushpanjali_count = excluded.pushpanjali_count';
        exception when undefined_column or invalid_text_representation then null; end;
    end if;

    -- Old user_locations(location_name, created_at)
    if to_regclass('public.user_locations') is not null then
        begin
            execute 'insert into public.live_locations (location, created_at) select location_name, created_at from public.user_locations where location_name is not null';
        exception when undefined_column then null; end;
    end if;
end;
$$;
